# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_100m]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk_100m]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {distance[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[6]}]
set_property PACKAGE_PIN W6 [get_ports {distance[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[5]}]
set_property PACKAGE_PIN U8 [get_ports {distance[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[4]}]
set_property PACKAGE_PIN V8 [get_ports {distance[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[3]}]
set_property PACKAGE_PIN U5 [get_ports {distance[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[2]}]
set_property PACKAGE_PIN V5 [get_ports {distance[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[1]}]
set_property PACKAGE_PIN U7 [get_ports {distance[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {distance[0]}]
set_property PACKAGE_PIN U2 [get_ports {sel[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property PACKAGE_PIN U4 [get_ports {sel[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property PACKAGE_PIN V4 [get_ports {sel[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property PACKAGE_PIN W4 [get_ports {sel[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
#Trig / Echo JA
set_property PACKAGE_PIN J1 [get_ports {Trig}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Trig}]
set_property PACKAGE_PIN L2 [get_ports {Echo}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Echo}]